TRAIN:
  ENABLE: True
  DATASET: mammalnet_behavior_composition
  BATCH_SIZE: 64
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 10
  AUTO_RESUME: False
  CHECKPOINT_FILE_PATH: "pretrained_models/c3d/c2d_baseline_8x8_IN_pretrain_400k.pkl"
  CHECKPOINT_EPOCH_RESET: True
  CHECKPOINT_TYPE: "caffe2"
  
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 24
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: "mammalnet_clips/composition_oneshot_perclass"
  DECODING_BACKEND: pyav
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 196
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 34.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES_BEHAVIOR: 13
  NUM_CLASSES_ANIMAL: 173
  ARCH: c2d
  MODEL_NAME: ResNet_composition
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: mammalnet_behavior_composition
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 6
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: results/I3D_composition_16x24_oneshot
